// Generated by CoffeeScript 1.10.0
var Router, db, protect, router;

Router = require('express').Router;

router = new Router;

db = require(routes + 'api/db');

protect = require(routes + 'protect');

router.use('/db', db);

router.get('/', function(req, res) {
  return res.json({
    message: 'asga Hasglo, world 21'
  });
});

router.post('/', function(req, res) {
  var id;
  id = req.body.id;
  console.log(id);
  return res.json(id);
});

router.get('/isprod', function(req, res) {
  var NODE_ENV;
  NODE_ENV = process.env.NODE_ENV;
  console.log(NODE_ENV);
  return res.json({
    production: NODE_ENV
  });
});

module.exports = router;
